apiVersion: v1
kind: Secret
metadata:
  name: csi-s3-secret
  namespace: default
stringData:
  accessKeyID: accesskeyid
  secretAccessKey: secret
  endpoint: "http://y126.l42scl.hortonworks.com:31475/"
  region: ""
  encryptionKey: ""
