apiVersion: v1
kind: Service
metadata:
  name: s3g-public
  namespace: poc
spec:
  ports:
    - port: 9878
      name: rest
      nodePort: 30878
  selector:
    app: ozone
    component: s3g
  type: NodePort
