apiVersion: v1
kind: Service
metadata:
  name: krb5
spec:
  ports:
  - port: 8081
    name: web
  clusterIP: None
  selector:
     app: krb5
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: krb5
spec:
  serviceName: krb5
  replicas: 1
  template:
    metadata:
      labels:
        app: krb5
    spec:
      containers:
        - name: krb5
          image: flokkr/krb5
