apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
  labels:
    app: vault
    component: vault
  annotations: {}
spec:
  replicas: 1
  serviceName: vault
  selector:
    matchLabels:
      app: vault
      component: vault
  template:
    metadata:
      labels:
        app: vault
        component: vault
      annotations: {}
    spec:
      containers:
        - name: vault
          image: vault
          env:
            - name: "VAULT_DEV_ROOT_TOKEN_ID"
              value: "devtoken"
