apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: datanode
spec:
  selector:
    matchLabels:
      app: ozone
      component: datanode
  template:
    metadata:
      labels:
        app: ozone
        component: datanode
    spec:
      containers:
        - name: datanode
          image: quay.io/ozonedev/ozone:214112b2d70
          args:
            - ozone
            - datanode
          ports:
            - containerPort: 9870
              name: rpc
          envFrom:
            - configMapRef:
                name: config
          volumeMounts:
            - name: "data"
              mountPath: "/data"
      volumes:
        - name: "data"
          emptyDir: {}
  serviceName: datanode
  replicas: 3
