apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: s3g
spec:
  selector:
    matchLabels:
      app: ozone
      component: s3g
  serviceName: s3g
  replicas: 1
  template:
    metadata:
      labels:
        app: ozone
        component: s3g
    spec:
      containers:
        - name: s3g
          image: quay.io/ozonedev/ozone:214112b2d70
          args:
            - ozone
            - s3g
          envFrom:
            - configMapRef:
                name: config
          volumeMounts:
            - name: "data"
              mountPath: "/data"
      volumes:
        - name: "data"
          emptyDir: {}
