apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: krb5
spec:
  serviceName: krb5
  replicas: 1
  template:
    metadata:
      labels:
        app: krb5
    spec:
      containers:
        - name: krb5
          image: flokkr/krb5
