apiVersion: v1
kind: ConfigMap
metadata:
  name: yarn-config
data:
  MAPRED-SITE.XML_mapreduce.framework.name: "yarn"
  MAPRED-SITE.XML_yarn.app.mapreduce.am.env: "HADOOP_MAPRED_HOME=/opt/hadoop"
  MAPRED-SITE.XML_mapreduce.map.env: "HADOOP_MAPRED_HOME=/opt/hadoop"
  MAPRED-SITE.XML_mapreduce.reduce.env: "HADOOP_MAPRED_HOME=/opt/hadoop"
  YARN-SITE.XML_yarn.resourcemanager.hostname: "yarn-resourcemanager-0.yarn-resourcemanager.default.svc.cluster.local"
  YARN-SITE.XML_yarn.resourcemanager.bind-host: "0.0.0.0"
  YARN-SITE.XML_yarn.nodemanager.bind-host: "0.0.0.0"
  YARN-SITE.XML_yarn.webapp.ui2.enable: "true"
  YARN-SITE.XML_yarn.nodemanager.pmem-check-enabled: "false"
  YARN-SITE.XML_yarn.nodemanager.delete.debug-delay-sec: "600"
  YARN-SITE.XML_yarn.nodemanager.vmem-check-enabled: "false"
  YARN-SITE.XML_yarn.nodemanager.aux-services: "mapreduce_shuffle"
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.maximum-applications: "10000"
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.maximum-am-resource-percent: "0.1"
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.resource-calculator: "org.apache.hadoop.yarn.util.resource.DefaultResourceCalculator"
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.root.queues: "default"
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.root.default.capacity: "100"
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.root.default.user-limit-factor: "1"
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.root.default.maximum-capacity: "100"
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.root.default.state: "RUNNING"
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.root.default.acl_submit_applications: "*"
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.root.default.acl_administer_queue: "*"
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.node-locality-delay: "40"
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.queue-mappings: ""
  CAPACITY-SCHEDULER.XML_yarn.scheduler.capacity.queue-mappings-override.enable: "false"
  CORE-SITE.XML_dfs.data.transfer.protection: "authentication"
  CORE-SITE.XML_hadoop.security.authentication: "kerberos"
  CORE-SITE.XML_hadoop.security.auth_to_local: "RULE:[2:$1@$0](.*)s/.*/hadoop/"
  SSL-SERVER.XML_ssl.server.keystore.location: "/opt/hadoop/etc/hadoop/hadoop.keystore"
  SSL-SERVER.XML_ssl.server.keystore.password: "Welcome1"
  SSL-SERVER.XML_ssl.server.keystore.keypassword: "Welcome1"
  SSL-SERVER.XML_ssl.server.truststore.location: "/opt/hadoop/etc/hadoop/truststore"
  SSL-SERVER.XML_ssl.server.truststore.password: "Welcome1"
  SSL-CLIENT.XML_ssl.client.keystore.location: "/opt/hadoop/etc/hadoop/hadoop.keystore"
  SSL-CLIENT.XML_ssl.client.keystore.password: "Welcome1"
  SSL-CLIENT.XML_ssl.client.keystore.keypassword: "Welcome1"
  SSL-CLIENT.XML_ssl.client.truststore.location: "/opt/hadoop/etc/hadoop/truststore"
  SSL-CLIENT.XML_ssl.client.truststore.password: "Welcome1"
  YARN-SITE.XML_yarn.resourcemanager.principal: "rm/_HOST@EXAMPLE.COM"
  YARN-SITE.XML_yarn.resourcemanager.keytab: "/opt/hadoop/etc/hadoop/rm.keytab"
  YARN-SITE.XML_yarn.nodemanager.principal: "nm/_HOST@EXAMPLE.COM"
  YARN-SITE.XML_yarn.nodemanager.keytab: "/opt/hadoop/etc/hadoop/nm.keytab"
  YARN-SITE.XML_yarn.timeline-service.principal: "ts/_HOST@EXAMPLE.COM"
  YARN-SITE.XML_yarn.timeline-service.keytab: "/opt/hadoop/etc/hadoop/ts.keytab"
  YARN-SITE.XML_yarn.web-proxy.principal: "wp/_HOST@EXAMPLE.COM"
  YARN-SITE.XML_yarn.web-proxy.keytab: "/opt/hadoop/etc/hadoop/wp.keytab"
  YARN-SITE.XML_yarn.resourcemanager.webapp.spnego-keytab-file: "/opt/hadoop/etc/hadoop/HTTP.keytab"
  YARN-SITE.XML_yarn.resourcemanager.webapp.spnego-principal: "HTTP/_HOST@EXAMPLE.COM"
  YARN-SITE.XML_yarn.nodemanager.webapp.spnego-keytab-file: "/opt/hadoop/etc/hadoop/HTTP.keytab"
  YARN-SITE.XML_yarn.nodemanager.webapp.spnego-principal: "HTTP/_HOST@EXAMPLE.COM"
  KERBEROS_KEYTABS: "HTTP rm ts wp nm"
  KERBEROS_KEYSTORES: "hadoop"
