apiVersion: apps/v1
kind: Deployment
metadata:
  name: freon
  labels:
    app.kubernetes.io/component: ozone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ozone
      component: freon
  template:
    metadata:
      labels:
        app: ozone
        component: freon
    spec:
      containers:
      - name: freon
        image: elek/ozone
        args: ["ozone","freon", "rk", "--factor=THREE", "--replicationType=RATIS"]
        envFrom:
           - configMapRef:
               name: config


