apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-storage
  labels: {}
  annotations: {}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-s3
