apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  prometheus.yaml: |-
   apiVersion: 1
   datasources:
   - name: prometheus
     type: prometheus
     access: proxy
     orgId: 1
     url: prometheus
     version: 1
     editable: false

