apiVersion: v1
kind: ConfigMap
metadata:
  name: hdfs-config
data:
  HDFS-SITE.XML_dfs.namenode.name.dir: "/data/namenode"
  LOG4J.PROPERTIES_log4j.rootLogger: "INFO, stdout"
  LOG4J.PROPERTIES_log4j.appender.stdout: "org.apache.log4j.ConsoleAppender"
  LOG4J.PROPERTIES_log4j.appender.stdout.layout: "org.apache.log4j.PatternLayout"
  LOG4J.PROPERTIES_log4j.appender.stdout.layout.ConversionPattern: "%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n"
  CORE-SITE.XML_fs.defaultFS: "hdfs://hdfs-namenode-0.hdfs-namenode:9820"
  HDFS-SITE.XML_dfs.namenode.rpc-address: "hdfs-namenode-0.hdfs-namenode:9820"

---
apiVersion: v1
kind: Service
metadata:
  name: hdfs-datanode
spec:
  ports:
    - port: 9874
      name: web
  clusterIP: None
  selector:
    app: hdfs
    component: datanode

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: hdfs-datanode
spec:
  serviceName: hdfs-datanode
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: hdfs
        component: datanode
    spec:
      containers:
        - name: hdfs-datanode
          image: flokkr/hadoop
          args:
            - hdfs
            - datanode
          env:
            - name: "WAITFOR"
              value: "hdfs-namenode-0.hdfs-namenode:9820"
          envFrom:
            - configMapRef:
                name: hdfs-config
      volumes:
        - name: config
          configMap:
            name: hdfs-config
        - name: "data"
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: hdfs-namenode
spec:
  clusterIP: None
  ports:
    - port: 9870
      name: web
  selector:
    app: hdfs
    component: namenode

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: hdfs-namenode
spec:
  serviceName: hdfs-namenode
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: hdfs
        component: namenode
    spec:
      initContainers:
        - name: hdfs-init
          image: flokkr/hadoop
          args:
            - hadoop
            - version
          env:
            - name: "ENSURE_NAMENODE_DIR"
              value: "/data/namenode"
          envFrom:
            - configMapRef:
                name: hdfs-config
          volumeMounts:
            - name: "data"
              mountPath: "/data"
      containers:
        - name: hdfs-namenode
          image: flokkr/hadoop
          args:
            - hdfs
            - namenode
          envFrom:
            - configMapRef:
                name: hdfs-config
          volumeMounts:
            - name: "data"
              mountPath: "/data"
      volumes:
        - name: "data"
          emptyDir: {}

---
