- type: Add
  path:
    - data
  value:
    CORE-SITE.XML_fs.defaultFS: hdfs://sh
    HDFS-SITE.XML_dfs.journalnode.edits.dir: /data/journalnode
    HDFS-SITE.XML_dfs.nameservices: sh
    HDFS-SITE.XML_dfs.ha.namenodes.sh: nn1,nn2
    HDFS-SITE.XML_dfs.namenode.rpc-address.sh.nn1: hdfs-namenode-0.hdfs-namenode:9820
    HDFS-SITE.XML_dfs.namenode.rpc-address.sh.nn2: hdfs-namenode2-0.hdfs-namenode2:9820
    HDFS-SITE.XML_dfs.ha.fencing.methods: shell(/bin/true)
    HDFS-SITE.XML_dfs.client.failover.proxy.provider.sh: org.apache.hadoop.hdfs.server.namenode.ha.ConfiguredFailoverProxyProvider
    HDFS-SITE.XML_dfs.ha.automatic-failover.enabled: "false"
    HDFS-SITE.XML_dfs.namenode.shared.edits.dir: qjournal://hdfs-journalnode-0.hdfs-journalnode:8485;hdfs-journalnode-1.hdfs-journalnode:8485;hdfs-journalnode-2.hdfs-journalnode:8485/sh
