apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka-broker
  annotations:
    flekszible/config-hash: "5b1d02c9181663714f64f8558b1eb9b0"
spec:
  serviceName: kafka-broker
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: kafka
        component: broker
    spec:
      containers:
        - name: kafka-broker
          image: flokkr/kafka
          env:
            - name: "WAITFOR"
              value: "zookeeper-0.zookeeper:2181"
          envFrom:
            - configMapRef:
                name: kafka-config
          args:
            - kafka-server-start.sh
            - /opt/kafka/config/server.cfg
      volumes:
        - name: "data"
          emptyDir: {}
