apiVersion: v1
kind: Service
metadata:
  name: yarn-resourcemanager
spec:
  ports:
  - port: 8088
    name: web
  clusterIP: None
  selector:
     app: yarn
     component: resourcemanager
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yarn-resourcemanager
  labels:
    app: yarn
    component: resourcemanager
spec:
  serviceName: yarn-resourcemanager
  replicas: 1 
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  selector:
     matchLabels:
        app: yarn
        component: resourcemanager
  template:
    metadata:
      labels:
        app: yarn
        component: resourcemanager
    spec:
      containers:
        - name: yarn-resourcemanager
          image: flokkr/hadoop
          args: ["yarn","resourcemanager"]
          envFrom:
             - configMapRef:
                  name: yarn-config
      volumes:
        - name: config
          configMap:
            name: yarn-config
        - name: data
          emptyDir: {}
