kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-s3
  labels: {}
  annotations: {}
  namespace: ozone
subjects:
  - kind: ServiceAccount
    name: csi-s3
    namespace: ozone
roleRef:
  kind: ClusterRole
  name: csi-s3
  apiGroup: rbac.authorization.k8s.io
