kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: csi-attacher-s3
  labels: {}
  annotations: {}
  namespace: ozone
spec:
  serviceName: csi-attacher-s3
  replicas: 1
  template:
    metadata:
      labels:
        app: csi-attacher-s3
      annotations: {}
    spec:
      serviceAccount: csi-attacher-sa
      containers:
        - name: csi-attacher
          image: quay.io/k8scsi/csi-attacher:v0.2.0
          args:
            - --v=4
            - --csi-address=$(ADDRESS)
          env:
            - name: "ADDRESS"
              value: "/var/lib/kubelet/plugins/ch.ctrox.csi.s3-driver/csi.sock"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/kubelet/plugins/ch.ctrox.csi.s3-driver
          envFrom: []
      volumes:
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/ch.ctrox.csi.s3-driver
            type: DirectoryOrCreate
