kind: Service
apiVersion: v1
metadata:
  name: csi-provisioner-s3
  labels:
    app: csi-provisioner-s3
  annotations: {}
  namespace: ozone
spec:
  selector:
    app: csi-provisioner-s3
  ports:
    - name: dummy
      port: 12345
