apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "ozone.fullname" . }}-datanode
  labels:
    apps.kubernetes.io/name: {{ include "ozone.name" . }}
    helm.sh/chart: {{ include "ozone.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations: {}
spec:
  selector:
    matchLabels:
      app: ozone
      component: datanode
  template:
    metadata:
      labels:
        app: ozone
        component: datanode
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "28942"
    spec:
      containers:
        - name: datanode
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          args:
            - ozone
            - datanode
          ports:
            - containerPort: 9870
              name: rpc
          volumeMounts:
            - name: "data"
              mountPath: "/data"
          env:
            - name: "PROMETHEUSJMX_ENABLED"
              value: "true"
            - name: "PROMETHEUSJMX_AGENTOPTS"
              value: "port=28942"
          envFrom:
            - configMapRef:
                name: {{ template "ozone.fullname" . }}-config
      volumes:
        - name: "data"
          emptyDir: {}
