apiVersion: v1
kind: Service
metadata:
  name: {{ template "ozone.fullname" . }}-s3g-public
  labels:
    apps.kubernetes.io/name: {{ include "ozone.name" . }}
    helm.sh/chart: {{ include "ozone.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations: {}
spec:
  ports:
    - port: 9878
      name: rest
  selector:
    app: ozone
    component: s3g
  type: NodePort
