- type: Add
  path:
    - data
  value:
     CORE-SITE.XML_dfs.data.transfer.protection: authentication
     CORE-SITE.XML_hadoop.security.authentication: kerberos
     CORE-SITE.XML_hadoop.security.auth_to_local: RULE:[2:$1@$0](.*)s/.*/hadoop/

     SSL-SERVER.XML_ssl.server.keystore.location: /opt/hadoop/etc/hadoop/hadoop.keystore
     SSL-SERVER.XML_ssl.server.keystore.password: Welcome1
     SSL-SERVER.XML_ssl.server.keystore.keypassword: Welcome1
     SSL-SERVER.XML_ssl.server.truststore.location: /opt/hadoop/etc/hadoop/truststore
     SSL-SERVER.XML_ssl.server.truststore.password: Welcome1
     SSL-CLIENT.XML_ssl.client.keystore.location: /opt/hadoop/etc/hadoop/hadoop.keystore
     SSL-CLIENT.XML_ssl.client.keystore.password: Welcome1
     SSL-CLIENT.XML_ssl.client.keystore.keypassword: Welcome1
     SSL-CLIENT.XML_ssl.client.truststore.location: /opt/hadoop/etc/hadoop/truststore
     SSL-CLIENT.XML_ssl.client.truststore.password: Welcome1

     YARN-SITE.XML_yarn.resourcemanager.principal: rm/_HOST@EXAMPLE.COM
     YARN-SITE.XML_yarn.resourcemanager.keytab: /opt/hadoop/etc/hadoop/rm.keytab
     YARN-SITE.XML_yarn.nodemanager.principal: nm/_HOST@EXAMPLE.COM
     YARN-SITE.XML_yarn.nodemanager.keytab: /opt/hadoop/etc/hadoop/nm.keytab
     YARN-SITE.XML_yarn.timeline-service.principal: ts/_HOST@EXAMPLE.COM
     YARN-SITE.XML_yarn.timeline-service.keytab: /opt/hadoop/etc/hadoop/ts.keytab
     YARN-SITE.XML_yarn.web-proxy.principal: wp/_HOST@EXAMPLE.COM
     YARN-SITE.XML_yarn.web-proxy.keytab: /opt/hadoop/etc/hadoop/wp.keytab
     YARN-SITE.XML_yarn.resourcemanager.webapp.spnego-keytab-file: /opt/hadoop/etc/hadoop/HTTP.keytab
     YARN-SITE.XML_yarn.resourcemanager.webapp.spnego-principal: HTTP/_HOST@EXAMPLE.COM
     YARN-SITE.XML_yarn.nodemanager.webapp.spnego-keytab-file: /opt/hadoop/etc/hadoop/HTTP.keytab
     YARN-SITE.XML_yarn.nodemanager.webapp.spnego-principal: HTTP/_HOST@EXAMPLE.COM

     YARN-SITE.XML_yarn.resourcemanager.hostname: "yarn-resourcemanager-0.yarn-resourcemanager.default.svc.cluster.local"

     KERBEROS_KEYTABS: HTTP rm ts wp nm
     KERBEROS_KEYSTORES: hadoop
